### ISSUE TITLE
Drag icons are broken (result in a crash)

### ISSUE THREAD

**Issue by ammen99** [ammen99/wayfire#33]

**Comment by AdrianVovk** [comment]
Do you mean DND?

**Comment by ammen99** [comment]
Yes

**Comment by AdrianVovk** [comment]
@ammen99 it's not just icons then. Occasionally dragging text in Epiphany will make everything freeze. The only way to fix this is to kill wayfire from another VTE

**Comment by ammen99** [comment]
drag icons is the wlroots term for everything you drag, including text snippets

**Comment by ammen99** [comment]
Resolved in master.
