### ISSUE TITLE
Port Wayfire to wlroots

### ISSUE THREAD

**Issue by ammen99** [ammen99/wayfire#4]
This issue is to track the progress of the wlr-wayfire port(in the wlroots branch). Feature development will stop until this is complete, although bugs will be fixed in the libweston version.

- [x] Use meson instead of cmake

- [x] Use wlr_log instead of built-in debugging file

- [x] Add some command line arguments (like `--config`)

- [x] Separate shell background and shell panel

- [x] Core

  - [x] input-manager
    - [x] keyboard
    - [x] pointer
    - [x] touch
    - [x] ~~tablet~~ - I have no hardware, so it is useless to do this now. If there are users who want tablet, then this can be implemented.
  - [x] render-manager
    - [x] basic rendering with damage tracking
    - [x] workspace_streams

  - [x] workspace-manager

  - [x] basic protocols
    - [x] xdg-shell-v6
    - [x] xwayland

  - [x] output configuration

    - [x] scale
    - [x] rotation 
    - [x] coordinates 

- [x] Plugins
  - [x]  move/resize
  - [x] command
  - [x] autostart
  - [x] rotator
  - [x] ~~screenshot~~ - deprecated in favor of the screenshot protocol, use external utilities like https://github.com/emersion/grim + command plugin.
  - [x] expo
  - [x] grid
  - [x] window-rules
  - [x] vswitch
  - [x] oswitch
  - [x] switcher
  - [x] apps-logger
  - [x] cube
  - [x] animate
  - [x] ~~backlight~~ - deprecated, use external utilities like https://github.com/haikarainen/light + command plugin
  - [x] tile - compiles, "works" but has many bugs, so this is a highly experimental and incomplete plugin

**Comment by AdrianVovk** [comment]
Since this is finished, can you close it?

**Comment by ammen99** [comment]
I'm waiting a bit more to test if there are many bugs or crashes. Maybe next week I'll close it, as the wlroots already has much more features than the libweston branch. I'll also have to update the README and such.

**Comment by ammen99** [comment]
Fixed in the `wlroots` branch. 99% of the functionality is already there or is in a better shape, there are a few nitpicks left.

**Comment by SirCmpwn** [comment]
Do you have plans on merging the wlroots branch into master?

**Comment by ammen99** [comment]
@SirCmpwn yes, of course. I'd first merge wobbly and decorations though, and add wlroots as a subproject. It changes too fast for me to constantly update, so I'd pin it to a specific commit or alpha release, and update the dependency only on wlroots release.
