### ISSUE TITLE
Implement SSD client support

### ISSUE THREAD

**Issue by ammen99** [ammen99/wayfire#8]
SSD client support in wayfire will feature in-compositor decorations. Here are some of the tasks left:

- [x] Compositor-drawn surfaces, which support pointer input
- [x] Basic implementation of decorations
- [x] Support kde-decoration-protocol so that we know whether the wayland client needs SSD
- [x] Update decoration title - requires newer wlroots
- [x] Disable/Hide frames for fullscreen surfaces

**Comment by AdrianVovk** [comment]
Isn't wlroots making their own protocol for this?

**Comment by ammen99** [comment]
No, they have protocol only to negotiate SSD or CSD (the kde-decoration-protocol). Our protocol is to allow 'decoration managers', i.e programs that actually draw decorations for other windows.

**Comment by AdrianVovk** [comment]
@ammen99 No I mean that (if I remember correctly) they were going to replace the KDE protocol with something new.

**Comment by ammen99** [comment]
@AdrianVovk Yes, they are working on a new protocol, but for the same purpose.

**Comment by ammen99** [comment]
Resolved in master.
